datasource:
  bkdb:
    host: 10.0.29.30
    port: 8123
    username: wuysh
    password: wys19851011
    schema: wystest
  chk8s:
    host: 10.0.29.21
    port: 8123
    username: wuysh
    password: wys19851011
    schema: default
  acdb:
    host: localhost
    port: 3306
    username: devtest
    password: 123123
    schema: acdb
  wuysh:
    host: localhost
    port: 3306
    username: devtest
    password: 123123
    schema: wuysh